//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoaC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.DONHANGCHITIETs = new HashSet<DONHANGCHITIET>();
        }
    
        public int ID_DH { get; set; }
        public int ID_KH { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public int ID_NV { get; set; }
        public string TEN_NHAN_VIEN { get; set; }
        public Nullable<System.DateTime> NGAY_MUA { get; set; }
        public Nullable<decimal> TONG_THANH_TOAN { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANGCHITIET> DONHANGCHITIETs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
