//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoaC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANGCHITIET
    {
        public int ID_DH { get; set; }
        public int ID_SP { get; set; }
        public Nullable<System.DateTime> NGAY_MUA { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public string DON_VI { get; set; }
        public Nullable<decimal> DON_GIA { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<decimal> THANH_TIEN { get; set; }
        public Nullable<decimal> TONG_THANH_TOAN { get; set; }
    }
}
