//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoaC_
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int ID_NV { get; set; }
        public string TEN_NHAN_VIEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string CHUCVU { get; set; }
    }
}
